SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN HR_GRADE AS G
ON E.EMP_NO	= G.EMP_NO
WHERE G.YEAR = '2022'
GROUP BY YEAR, EMP_NO
ORDER BY SCORE DESC
LIMIT 1